apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: emoji-voto
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/christian1607/gitops-clusters-management