apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: emoji-voto
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: 'https://github.com/christian1607/gitops-clusters-management'
  #secretRef:
  #  name: git-repo-credentials
  #gitImplementation: libgit2

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: emoji-voto
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps/kind-local
  prune: true
  sourceRef:
    kind: GitRepository
    name: emoji-voto
